Study-With-Me-JJ/swm-backend

- .gitignore
- docker-compose.yaml
DB 연결 및 docker-compose.yaml 작성
- [SWM-7] DB 연결 및 docker-compose.yaml 작성
[SWM-7]: https://rosoa0475.atlassian.net/browse/SWM-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SWM-7] DB 연결 및 docker-compose.yaml 작성

- build.gradle
- src/main/java/com/jj/swm/infra/redis/RedisConfig.java
Redis 추가 및 Spring Boot Cache 추가
- RedissonClient 추가
- Spring Boot Cache 추가
> [SWM-8] redis 연결 추가

- build.gradle
- src/main/java/com/jj/swm/infra/s3/S3ClientWrapper.java
- src/main/resources/application.yml
S3Client 추가
- S3Client 추가
- PutObject 추가
> [SWM-9] S3Client 추가

- src/main/java/com/jj/swm/SwmBackendApplication.java
- src/main/java/com/jj/swm/domain/user/entity/RoleType.java
- src/main/java/com/jj/swm/domain/user/entity/User.java
- src/main/java/com/jj/swm/global/common/entity/BaseTimeEntity.java
- src/main/resources/application.yml
- src/main/resources/db/migration/V20241129204647__create_user_table.sql
User Entity 생성 및 BaseTimeEntity 생성, RoleType 생성
- User Entity 생성 및 BaseTimeEntity 생성, RoleType 생성
> [SWM-13] User Entity 생성 및 BaseTimeEntity 생성

- src/main/java/com/jj/swm/domain/user/entity/User.java
User Enumerated String으로 수정
- User Enumerated String으로 수정
> [HOTFIX/SWM-31] User Enumerated String으로 수정

- src/main/java/com/jj/swm/domain/study/entity/StudyTag.java
- src/main/resources/db/migration/V20241130132009__create_study_tag_table.sql
study tag entity 생성
- flyway 마이그레이션 파일 생성 및 study tag entity 생성
> [SWM-24] study tag entity 생성

- build.gradle
- src/main/java/com/jj/swm/SwmBackendApplication.java
- src/main/java/com/jj/swm/crawling/naver/map/constants/KoreaRegion.java
- src/main/java/com/jj/swm/crawling/naver/map/entity/ExternalStudyRoom.java
- src/main/java/com/jj/swm/crawling/naver/map/repository/ExternalStudyRoomRepository.java
- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/main/java/com/jj/swm/global/common/entity/BaseTimeEntity.java
- src/main/resources/application.yml
- src/main/resources/db/migration/V20241130152331__create_table_external_study_room.sql
- src/main/resources/db/migration/V20241130155213__alter_table_external_study_room.sql
네이버 지도 스터디룸 크롤링
- 네이버 지도 스터디룸 크롤링
> [SWM-11] 네이버 지도 스터디룸 크롤링

- src/main/java/com/jj/swm/domain/study/entity/StudyImage.java
- src/main/resources/db/migration/V20241130160214__create_study_image_table.sql
study image entity 생성
- study image entity 생성
> [SWM-25]: study image entity 생성

- src/main/java/com/jj/swm/domain/user/entity/User.java
유저 역할 postgresql DB Enum 매핑
- 유저 역할 postgresql DB Enum 매핑
> [SWM-32] 유저 역할 postgresql DB Enum 매핑

- src/main/java/com/jj/swm/domain/study/entity/StudyRecruitmentPosition.java
- src/main/resources/db/migration/V20241130163016__create_study_recruitment_position_table.sql
study recruitment position entity 생성
- study recruitment position entity 생성
> [SWM-26]: study recruitment position entity 생성

- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
네이버 지도 크롤링 버그 수정
- 네이버 지도 크롤링 버그 수정
> [SWM-11] 네이버 지도 크롤링 버그 수정

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReview.java
- src/main/resources/db/migration/V20241130171240__create_study_room_review_table.sql
스터디 룸 리뷰 엔티티 생성
- 스터디 룸 리뷰 엔티티 생성
> [SWM-17] 스터디 룸 리뷰 엔티티 생성

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomQna.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReview.java
- src/main/resources/db/migration/V20241130175314__create_study_room_qna_table.sql
스터디 룸 QnA 엔티티 생성
- 스터디 룸 리뷰 SQLDelete 설정 변경
- 스터디 룸 QnA 엔티티 생성
> [SWM-18] 스터디 룸 QnA 엔티티 생성

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomLike.java
- src/main/resources/db/migration/V20241130211546__create_study_room_like_table.sql
스터디 룸 좋아요 엔티티 생성, Flyway sql 파일 생성
- 스터디 룸 좋아요 엔티티 생성, Flyway sql 파일 생성
> [SWM-19] 스터디 룸 좋아요 엔티티 생성

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomBookmark.java
- src/main/resources/db/migration/V20241130212734__create_study_room_bookmark_table.sql
스터디 룸 북마크 엔티티 생성, Flyway study_room_bookrmark sql 파일 생성
- 스터디 룸 북마크 엔티티 생성, Flyway study_room_bookrmark sql 파일 생성
> feat: 스터디 룸 북마크 엔티티 생성

- src/main/java/com/jj/swm/domain/study/entity/StudyParticipant.java
- src/main/java/com/jj/swm/domain/study/entity/StudyParticipantStatus.java
- src/main/resources/db/migration/V20241130165303__create_study_participant_table.sql
study participant entity 생성
- study participant status enum 생성
- study participant entitiy 생성
> [SWM-27]: study participant entity 생성

- src/main/java/com/jj/swm/domain/study/entity/StudyBookmark.java
- src/main/resources/db/migration/V20241201001207__create_study_bookmark_table.sql
study bookmark entity 생성
- study bookmark entity 생성
> [SWM-28]: study bookmark entity 생성

- src/main/java/com/jj/swm/domain/study/entity/StudyComment.java
- src/main/resources/db/migration/V20241201002658__create_study_comment_table.sql
study comment entity 생성
- study comment entity 생성
> [SWM-29]: study comment entity 생성

- src/main/java/com/jj/swm/domain/study/entity/StudyLike.java
- src/main/resources/db/migration/V20241201004749__create_study_like_table.sql
study like entity 생성
- study like entity 생성
> [SWM-30]: study like entity 생성

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoom.java
- src/main/resources/db/migration/V20241201005555__alter_table_study_room_add_min_reserve_time.sql
- src/main/resources/db/migration/V20241201010905__alter_table_study_room_add_entire_min_headcount_and_max_headcount.sql
스터디 룸 엔티티 예약시간, 최소/최대 인원 추가, Flyway alter sql 추가
- 스터디 룸 엔티티 예약시간, 최소/최대 인원 추가, Flyway alter sql 추가
> [SWM-37] 스터디 룸 엔티티 예약시간, 최소/최대 인원 추가, Flyway alter sql 추가

- src/main/java/com/jj/swm/domain/study/entity/Study.java
study 엔티티의 enum과 db의 enum을 연동하기 위한 어노테이션 추가
- study 엔티티의 enum과 db의 enum을 연동하기 위한 어노테이션 추가
> [SWM-39]: study 엔티티의 enum과 db의 enum을 연동하기 위한 어노테이션 추가

- src/main/java/com/jj/swm/domain/study/entity/StudyComment.java
study comment 엔티티에 soft delete를 위한 어노테이션 추가
- study comment 엔티티에 soft delete를 위한 어노테이션 추가
> [SWM-40]: study comment 엔티티에 soft delete를 위한 어노테이션 추가

- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/main/java/com/jj/swm/infra/s3/S3ClientWrapper.java
- src/main/java/com/jj/swm/infra/s3/S3KeyGenerator.java
[SWM-11] 네이버 지도 크롤링 버그 픽스
- [SWM-11] 네이버 지도 크롤링 버그 픽스
[SWM-11]: https://rosoa0475.atlassian.net/browse/SWM-11?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SWM-11]: https://rosoa0475.atlassian.net/browse/SWM-11?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SWM-11] 네이버 지도 크롤링 버그 픽스

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReviewReply.java
- src/main/resources/db/migration/V20241201134003__create_study_room_review_reply.sql
스터디 룸 이용 후기 답글 엔티티 생성 및 Flyway create sql 추가
- 스터디 룸 이용 후기 답글 엔티티 생성 및 Flyway create sql 추가
> [SWM-33 스터디 룸 이용 후기 답글 엔티티 생성 및 Flyway create sql 추가

- build.gradle
> [SWM-41] 스웨거 추가

- src/main/resources/application.yml
> [SWM-41] 스웨거 설정 변경

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomTag.java
- src/main/resources/db/migration/V20241201135440__create_study_room_tag_table.sql
스터디 룸 태그 엔티티 생성 및 Flyway create sql 추가
- 스터디 룸 태그 엔티티 생성 및 Flyway create sql 추가
> [SWM-34] 스터디 룸 태그 엔티티 생성 및 Flyway create sql 추가

- Dockerfile
> [SWM-42] Dockerfile 제작

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomType.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomTypeInfo.java
- src/main/resources/db/migration/V20241201141746__create_study_room_type_info_table.sql
스터디 룸 유형 정보 엔티티 생성 및 Flyway create sql 추가
- 스터디 룸 유형 정보 엔티티 생성 및 Flyway create sql 추가
> [SWM-35] 스터디 룸 유형 정보 엔티티 생성 및 Flyway create sql 추가

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomOption.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomOptionInfo.java
- src/main/resources/db/migration/V20241201150902__create_study_room_option_info_table.sql
스터디 룸 옵션 정보 엔티티 생성 및 Flyway create sql 추가
- 스터디 룸 옵션 정보 엔티티 생성 및 Flyway create sql 추가
> [SWM-14] 스터디 룸 옵션 정보 엔티티 생성 및 Flyway create sql 추가

- src/main/resources/db/migration/V20241201152857__alter_all_table_related_study_room.sql
bigserial 관련 시퀀스, default 삭제
- bigserial 관련 시퀀스, default 삭제
> [HOTFIX/SWM-44] bigserial 관련 시퀀스, default 삭제

- src/main/resources/db/migration/V20241201154854__alter_table_study_room_review_reply_reference.sql
스터디 이용 후기 답글 엔티티 참조 수정
- 스터디 이용 후기 답글 엔티티 참조 수정
> [HOTFIX/SWM-45] 스터디 이용 후기 답글 엔티티 참조 수정

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoom.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomBookmark.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomLike.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomQna.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReserveType.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReview.java
- src/main/resources/db/migration/V20241130171240__create_study_room_review_table.sql
- src/main/resources/db/migration/V20241130175314__create_study_room_qna_table.sql
- src/main/resources/db/migration/V20241130211546__create_study_room_like_table.sql
- src/main/resources/db/migration/V20241130212734__create_study_room_bookmark_table.sql
- src/main/resources/db/migration/V20241130213745__create_study_room_reserve_type_table.sql
- src/main/resources/db/migration/V20241201005555__alter_table_study_room_add_min_reserve_time.sql
- src/main/resources/db/migration/V20241201010905__alter_table_study_room_add_entire_min_headcount_and_max_headcount.sql
[Revert/SWM-37] Revert된 엔티티 추가
> [Revert/SWM-37] Revert된 엔티티 추가

- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
셀레니움 컨테이너 환경 오류 해결
- 셀레니움 컨테이너 환경 오류 해결
> [SWM-46] 셀레니움 컨테이너 환경 오류 해결

- src/main/resources/db/migration/V20241201210644__alter_all_table_related_study.sql
스터디 관련 연관관계 엔티티 bigserial 관련 시퀀스, default 삭제
- 스터디 관련 연관관계 엔티티 bigserial 관련 시퀀스, default 삭제
> [SWM-48]: 스터디 관련 연관관계 엔티티 bigserial 관련 시퀀스, default 삭제

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomImage.java
- src/main/resources/db/migration/V20241201211305__create_study_room_image_table.sql
스터디 룸 이미지 엔티티 생성 및 Flyway create sql 추가
- 스터디 룸 이미지 엔티티 생성 및 Flyway create sql 추가
> [SWM-47] 스터디 룸 이미지 엔티티 생성 및 Flyway create sql 추가

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomBookmark.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomLike.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomOptionInfo.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomTypeInfo.java
- src/main/resources/db/migration/V20241201213853__alter_few_table_drop_column_deleted_and_basetime.sql
SOFT DELETE 적용, 비적용 엔티티 구분
- study_room_bookmark deleted_at, created_at, updated_at 제거
- study_room_like deleted_at, created_at, updated_at 제거
- study_room_option_info deleted_at, created_at, updated_at 제거
- study_room_type_info deleted_at, created_at, updated_at 제거
> [SWM-49] SOFT DELETE 적용, 비적용 엔티티 구분

- src/main/java/com/jj/swm/domain/study/entity/StudyRecruitmentPosition.java
- src/main/java/com/jj/swm/domain/study/entity/StudyTag.java
- src/main/resources/db/migration/V20241201215211__alter_table_study_tag_add_deleted_at.sql
- src/main/resources/db/migration/V20241201215745__alter_table_study_recruitment_position_add_deleted_at.sql
스터디 태그, 모집 직무 엔티티에 soft delete 적용
- 스터디 태그, 모집 직무 엔티티에 soft delete 적용
> [SWM-50]: 스터디 태그, 모집 직무 엔티티에 soft delete 적용

- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomDayOff.java
- src/main/resources/db/migration/V20241202220315__create_study_room_day_off_table.sql
스터디 룸 휴무일 엔티티 추가
- 스터디 룸 휴무일 엔티티 추가
> [SWM-54] 스터디 룸 휴무일 엔티티 추가

- src/main/java/com/jj/swm/domain/user/controller/UserCommandController.java
- src/main/java/com/jj/swm/domain/user/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/repository/UserRepository.java
- src/main/java/com/jj/swm/domain/user/service/UserCommandService.java
- src/main/java/com/jj/swm/domain/user/service/UserQueryService.java
유저 관련 각 계층 별 클래스 생성
- UserRepository 생성
- UserCommandService 생성
- UserQueryService 생성
- UserCommandController 생성
- UserQueryController 생성
> [SWM-56]: 유저 관련 각 계층 별 클래스 생성

- src/main/java/com/jj/swm/domain/user/repository/UserRepository.java
UserRepository 기본키 타입 변경
- UserRepository 기본키 타입 변경
> [SWM-57]: UserRepository 기본키 타입 변경

- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/java/com/jj/swm/domain/study/entity/StudyBookmark.java
- src/main/java/com/jj/swm/domain/study/entity/StudyComment.java
- src/main/java/com/jj/swm/domain/study/entity/StudyImage.java
- src/main/java/com/jj/swm/domain/study/entity/StudyLike.java
- src/main/java/com/jj/swm/domain/study/entity/StudyParticipant.java
- src/main/java/com/jj/swm/domain/study/entity/StudyRecruitmentPosition.java
- src/main/java/com/jj/swm/domain/study/entity/StudyTag.java
스터디 관련 엔티티 기본 키 전략 SEQUENCE로 변경
- 스터디 관련 엔티티 기본 키 전략 SEQUENCE로 변경
> [SWM-58]: 스터디 관련 엔티티 기본 키 전략 SEQUENCE로 변경

- .gitignore
- build.gradle
- src/test/java/com/jj/swm/SwmBackendApplicationTests.java
TestContainers 세팅
- TestContainers 세팅
> [SWM-59] TestContainers

- Dockerfile
- src/main/java/com/jj/swm/SwmBackendApplication.java
- src/main/java/com/jj/swm/crawling/config/ChromeDriverConfig.java
- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/main/java/com/jj/swm/domain/common/KoreaRegion.java
- src/main/java/com/jj/swm/domain/external/study/controller/ExternalStudyRoomController.java
- src/main/java/com/jj/swm/domain/external/study/dto/response/ExternalStudyRoomOutput.java
- src/main/java/com/jj/swm/domain/external/study/dto/response/GetExternalStudyRoomsResponse.java
- src/main/java/com/jj/swm/domain/external/study/entity/ExternalStudyRoom.java
- src/main/java/com/jj/swm/domain/external/study/repository/ExternalStudyRoomRepository.java
- src/main/java/com/jj/swm/domain/external/study/service/ExternalStudyRoomService.java
외부 스터디룸 API 추가
- 외부 스터디룸 API 추가
- 셀레니움 문제 해결
> [SWM-43] 외부 스터디룸 API 추가

- src/main/java/com/jj/swm/SwmBackendApplication.java
- src/main/java/com/jj/swm/global/config/JpaConfig.java
컨트롤러 단위 테스트 시에 @EnableJpaAuditing 충돌 해결
- 컨트롤러 단위 테스트 시에 @EnableJpaAuditing 충돌 해결
> [SWM-61]: 컨트롤러 단위 테스트 시에 @EnableJpaAuditing 충돌 해결

- src/main/java/com/jj/swm/domain/study/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyRecruitPositionsCreateRequest.java
- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/java/com/jj/swm/domain/study/entity/StudyImage.java
- src/main/java/com/jj/swm/domain/study/entity/StudyRecruitmentPosition.java
- src/main/java/com/jj/swm/domain/study/entity/StudyTag.java
- src/main/java/com/jj/swm/domain/study/repository/JdbcStudyImageRepository.java
- src/main/java/com/jj/swm/domain/study/repository/JdbcStudyImageRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/repository/JdbcStudyRecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/repository/JdbcStudyRecruitmentPositionRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/repository/JdbcStudyTagRepository.java
- src/main/java/com/jj/swm/domain/study/repository/JdbcStudyTagRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/repository/StudyImageRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyRecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyTagRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
- src/test/java/com/jj/swm/domain/study/controller/StudyCommandControllerTest.java
- src/test/java/com/jj/swm/domain/study/service/StudyCommandServiceTest.java
스터디 생성 api 추가
- 스터디 생성 로직 개발
- 스터디 생성 로직에 대한 컨트롤러, 서비스 계층 단위 테스트 작성
- 스터디 관련 엔티티 내에 정적 팩토리 메소드 작성
- 스터디 생성 관련 request dto 생성
> [SWM-55]: 스터디 생성 api 추가

- src/main/java/com/jj/swm/global/config/QueryInspectorConfig.java
- src/main/java/com/jj/swm/global/filter/LatencyLoggingFilter.java
- src/main/java/com/jj/swm/global/filter/LatencyRecorder.java
- src/main/java/com/jj/swm/global/filter/QueryCounter.java
- src/main/java/com/jj/swm/global/filter/QueryInspector.java
API Latency와 쿼리 개수를 확인을 위한 QueryInspector 생성
- API Latency와 쿼리 개수를 확인을 위한 QueryInspector 생성
> [SWM-65] API Latency와 쿼리 개수를 확인을 위한 QueryInspector 생성

- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/main/resources/application.yml
네이버 지도 크롤링 스크롤 버그 픽스
- 네이버 지도 크롤링 스크롤 버그 픽스
> [SWM-68] 네이버 지도 크롤링 스크롤 버그 픽스

- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/test/java/com/jj/swm/IntegrationContainerSupporter.java
테스트 컨테이너 추상 클래스
- 테스트 컨테이너 추상 클래스
> [SWM-67] 테스트 컨테이너 추상 클래스

- src/main/java/com/jj/swm/domain/study/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyBookmarkCreateResponse.java
- src/main/java/com/jj/swm/domain/study/entity/StudyBookmark.java
- src/main/java/com/jj/swm/domain/study/repository/StudyBookmarkRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
- src/test/java/com/jj/swm/domain/study/controller/StudyCommandControllerTest.java
- src/test/java/com/jj/swm/domain/study/service/StudyCommandServiceTest.java
스터디 북마크 생성, 삭제 api 추가
- 스터디 북마크 생성 api 추가
- 스터디 북마크 삭제 api 추가
- StudyCommandControllerTest 줄바꿈 리팩토링
- StudyCommandServiceTest 줄바꿈, 중복 코드 메소드로 추출 리팩토링
- 스터디 북마크 생성 컨트롤러 단위 테스트 생성
- 스터디 북마크 삭제 컨트롤러 단위 테스트 생성
- 스터디 북마크 생성 서비스 단위 테스트 생성
- 스터디 북마크 삭제 서비스 단위 테스트 생성
> [SWM-64]: 스터디 북마크 생성, 삭제 api 추가

- src/main/java/com/jj/swm/global/common/dto/ApiResponse.java
- src/main/java/com/jj/swm/global/common/enums/ErrorCode.java
- src/main/java/com/jj/swm/global/exception/handler/SWMExceptionHandler.java
@RestControllerAdvice 추가
- @RestControllerAdvice 추가
- NOT_VALID, INTERNAL_SERVER_ERROR ErrorCode 값 추가
> [SWM-71] @RestControllerAdvice 추가

- src/test/java/com/jj/swm/domain/studyroom/controller/StudyRoomCommandControllerTest.java
> [REFACTOR/SWM-69] 일관성을 위해 public 접근제어자 제거

- build.gradle
- src/main/java/com/jj/swm/global/config/JpaConfig.java
QueryDSL 의존성 추가 및 JPAQueryFactory 빈 생성
- QueryDSL 의존성 추가 및 JPAQueryFactory 빈 생성
> [SWM-73]: QueryDSL 의존성 추가 및 JPAQueryFactory 빈 생성

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomCreateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomDeleteRequest.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomDayOffRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomImageRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomOptionInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomTagRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomTypeInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
StudyRoom DELETE API 작성
- StudyRoom DELETE API 작성
추후, 좋아요, 이용후기, 이용후기 답글, QnA, QnA 답글, 좋아요 수, 북마크 수 삭제 필요
> [SWM-75] StudyRoom DELETE API 작성

- src/main/java/com/jj/swm/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
스터디 모집 직무 create dto 변경 및 이에 따른 서비스 계층 로직 수정
- 스터디 create request dto 변경
- 스터디 create service 로직 변경
> [SWM-77]: 스터디 모집 직무 create dto 변경 및 이에 따른 서비스 계층 로직 수정

- src/main/java/com/jj/swm/domain/study/repository/StudyBookmarkRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
북마크 생성 시 중복 검증 추가 및 북마크 삭제 로직에 @Transactional 추가
- 북마크 삭제 로직에 @Transactional 추가
- 북마크 생성 시 중복 검증 추가
> [SWM-78]: 북마크 생성 시 중복 검증 추가 및 북마크 삭제 로직에 @Transactional 추가

- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/main/java/com/jj/swm/infra/s3/S3ClientWrapper.java
PresignedURL 추가, 셀레니움 시간 수정
- PresignedURL 추가
- 셀레니움 시간 수정
> [SWM-80] PresignedURL

- src/main/java/com/jj/swm/domain/study/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyImageModifyRequest.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyRecruitPositionModifyRequest.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyRecruitPositionUpdateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyTagModifyRequest.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyUpdateRequest.java
- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/java/com/jj/swm/domain/study/entity/StudyRecruitmentPosition.java
- src/main/java/com/jj/swm/domain/study/repository/StudyImageRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyRecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyTagRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
Study 업데이트 api 추가
- Study 업데이트 관련 dto 생성
- Study, StudyRecruitmentPosition 엔티티 내에 수정 메소드 추가
- StudyImage, StudyTag Repository 배치 삭제 메소드 추가
- StudyRecruitmentPosition 배치 삭제 메소드 & find 메소드 추가
> [SWM-79]: Study 업데이트 api 추가

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomUpdateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomUpdateSettingRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/update/dayoff/StudyRoomDayOffModifyRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/update/option/StudyRoomOptionInfoModifyRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/update/reservationType/StudyRoomReservationTypeModifyRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/update/tag/StudyRoomTagModifyRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/update/type/StudyRoomTypeInfoModifyRequest.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
StudyRoom Update API 리팩토링
- StudyRoom Update API 리팩토링
- Update API 간소화
- 중복 코드 간소화
> [REFACTOR/SWM-81] StudyRoom Update API 리팩토링

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/StudyRoomLikeCreateResponse.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomLikeRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandServiceTest.java
StudyRoomLike create, delete, test 리팩토링
- StudyRoomLike create, delete, test 리팩토링
- delete API에서 studyRoomLikeId PathVariable 제거
- 테스트 코드 @AfterEach에 DB에 저장한 데이터 초기화 로직 추가
> refactor: StudyRoomLike create, delete, test 리팩토링

- src/main/java/com/jj/swm/crawling/holaworld/service/HolaWorldCrawlingService.java
- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/main/java/com/jj/swm/domain/external/study/entity/ExternalStudy.java
- src/main/java/com/jj/swm/domain/external/study/repository/ExternalStudyRepository.java
- src/main/java/com/jj/swm/domain/external/studyroom/controller/ExternalStudyRoomController.java
- src/main/java/com/jj/swm/domain/external/studyroom/dto/response/ExternalStudyRoomOutput.java
- src/main/java/com/jj/swm/domain/external/studyroom/dto/response/GetExternalStudyRoomsResponse.java
- src/main/java/com/jj/swm/domain/external/studyroom/entity/ExternalStudyRoom.java
- src/main/java/com/jj/swm/domain/external/studyroom/repository/ExternalStudyRoomRepository.java
- src/main/java/com/jj/swm/domain/external/studyroom/service/ExternalStudyRoomService.java
- src/main/resources/db/migration/V20241209224357__create_table_external_study.sql
> [SWM-87] 홀라 스터디 크롤링

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoom.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandServiceTest.java
스터디 룸 좋아요 네이밍 및 테스트 리팩토링
- 스터디 룸 좋아요 네이밍 및 테스트 리팩토링
> [REFACTOR/SWM-89] 스터디 룸 좋아요 네이밍 및 테스트 리팩토링

- src/main/java/com/jj/swm/domain/study/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyLikeCreateResponse.java
- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/java/com/jj/swm/domain/study/entity/StudyLike.java
- src/main/java/com/jj/swm/domain/study/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
- src/test/java/com/jj/swm/domain/study/StudyFixture.java
- src/test/java/com/jj/swm/domain/study/StudyLikeFixture.java
- src/test/java/com/jj/swm/domain/study/service/StudyCommandServiceConcurrencyTest.java
- src/test/java/com/jj/swm/domain/user/UserFixture.java
스터디 좋아요, 좋아요 취소 api 추가
- 스터디 좋아요 api 추가
- 스터디 좋아요 취소 api 추가
> [SWM-85]: 스터디 좋아요, 좋아요 취소 api 추가

- src/main/java/com/jj/swm/domain/study/entity/StudyComment.java
- src/main/resources/db/migration/V20241210152425__alter_table_study_comment_add_parent_id.sql
댓글 셀프조인 flyway 추가 및 엔티티 수정
- 댓글 셀프조인 flyway 추가 및 엔티티 수정
> [SWM-91]: 댓글 셀프조인 flyway 추가 및 엔티티 수정

- src/main/java/com/jj/swm/domain/study/controller/CommentCommandController.java
- src/main/java/com/jj/swm/domain/study/dto/request/CommentUpsertRequest.java
- src/main/java/com/jj/swm/domain/study/dto/response/CommentUpdateResponse.java
- src/main/java/com/jj/swm/domain/study/entity/StudyComment.java
- src/main/java/com/jj/swm/domain/study/repository/CommentRepository.java
- src/main/java/com/jj/swm/domain/study/service/CommentCommandService.java
> [SWM-51]: 댓글 수정 api 추가

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomReviewCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewCreateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewReplyCreateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewReplyUpdateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewUpdateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/StudyRoomReviewCreateResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/StudyRoomReviewReplyCreateResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/StudyRoomReviewUpdateResponse.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoom.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReview.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReviewReply.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReviewReplyRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReviewRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewCommandService.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandServiceTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewCommandServiceTest.java
스터디 룸 이용후기, 이용후기 답글 CREATE, UPDATE API 및 테스트 개발
- 스터디 룸 이용후기, 답글 CREATE, UPDATE API 및 테스트 개발
- 스터디 룸 북마크 네이밍 정정
- 스터디 룸 서비스 테스트 리팩토링
> [FEAT/SWM-84] 

- src/main/java/com/jj/swm/domain/study/controller/CommentCommandController.java
- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/java/com/jj/swm/domain/study/entity/StudyComment.java
- src/main/java/com/jj/swm/domain/study/repository/CommentRepository.java
- src/main/java/com/jj/swm/domain/study/service/CommentCommandService.java
댓글 생성 api 수정 및 댓글 삭제 api 추가
- 댓글 삭제된 상황에서 대댓글 생성 시 일반 댓글로 생성되는 버그 수정
- 댓글 생성시 depth 1이 되도록 수정
- 댓글 삭제 api 추가
> [SWM-94]: 댓글 생성 api 수정 및 댓글 삭제 api 추가

- src/main/java/com/jj/swm/domain/external/study/controller/ExternalStudyController.java
- src/main/java/com/jj/swm/domain/external/study/dto/response/ExternalStudyDto.java
- src/main/java/com/jj/swm/domain/external/study/dto/response/GetExternalStudiesResponse.java
- src/main/java/com/jj/swm/domain/external/study/repository/ExternalStudyRepository.java
- src/main/java/com/jj/swm/domain/external/study/service/ExternalStudyService.java
- src/main/java/com/jj/swm/domain/external/studyroom/controller/ExternalStudyRoomController.java
- src/main/java/com/jj/swm/domain/external/studyroom/repository/ExternalStudyRoomRepository.java
- src/main/java/com/jj/swm/domain/external/studyroom/service/ExternalStudyRoomService.java
스터디 조회 API 및 외부 스터디룸 조회 API 변경
- 외부 스터디 조회 API
- 외부 스터디룸 조회 API 변경
> [SWM-98] 외부 스터디 조회 API 및 외부 스터디룸 조회 API 변경

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQnaCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomQnaUpsertRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/StudyRoomQnaCreateResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/StudyRoomQnaUpdateResponse.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomQna.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomQnaRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaCommandService.java
- src/main/resources/db/migration/V20241211151153__alter_table_study_room_qna_seq_and_parent.sql
- src/test/java/com/jj/swm/domain/studyroom/StudyRoomQnaFixture.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandServiceTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaCommandServiceTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewCommandServiceTest.java
- src/test/java/com/jj/swm/domain/user/UserFixture.java
스터디 룸 QnA CUD API 추가 및 테스트 코드 작성
- 스터디 룸 QnA CUD API 추가 및 테스트 코드 작성
- UserFixture 메소드 네이밍 변경
> [FEAT/SWM-90] 스터디 룸 QnA CUD API 추가 및 테스트 코드 작성

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomReviewCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewCreateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewReplyCreateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewReplyUpdateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomReviewUpdateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomUpdateRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/StudyRoomUpdateSettingRequest.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomQnaRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaCommandService.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewCommandService.java
- src/test/java/com/jj/swm/IntegrationContainerSupporter.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaCommandServiceTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewCommandServiceTest.java
RESTful 규칙에 맞게 PathVariable로 리팩토링
- RESTful 규칙에 맞게 PathVariable로 리팩토링
> [REFACTOR/SWM-99] RESTful 규칙에 맞게 PathVariable로 리팩토링

- src/main/java/com/jj/swm/domain/study/controller/StudyQueryController.java
- src/main/java/com/jj/swm/domain/study/dto/ParticipantStatusInfo.java
- src/main/java/com/jj/swm/domain/study/dto/ReplyCountInfo.java
- src/main/java/com/jj/swm/domain/study/dto/StudyPositionAcceptedCountInfo.java
- src/main/java/com/jj/swm/domain/study/dto/response/CommentInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyDetailsResponse.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyImageInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyRecruitPositionInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/java/com/jj/swm/domain/study/entity/StudyParticipantStatus.java
- src/main/java/com/jj/swm/domain/study/repository/CommentRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyImageRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyRecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyQueryService.java
- src/main/java/com/jj/swm/global/common/dto/PageResponse.java
- src/main/resources/application.yml
스터디 상세 조회 api 추가
- page size에 대한 @Value 어노테이션 컨트롤러 인자에서 서비스 계층 필드로 이동
- 목록 조회시에 조회하는 유저가 쓴 글인지에 대한 데이터 전송
- Study 상세 조회 api 추가
> [SWM-97]: 스터디 상세 조회 api 추가

- src/main/java/com/jj/swm/domain/study/controller/CommentQueryController.java
- src/main/java/com/jj/swm/domain/study/dto/response/ReplyInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/repository/CommentRepository.java
- src/main/java/com/jj/swm/domain/study/repository/CustomCommentRepository.java
- src/main/java/com/jj/swm/domain/study/repository/CustomCommentRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/service/CommentQueryService.java
- src/main/java/com/jj/swm/domain/study/service/StudyQueryService.java
- src/main/resources/application.yml
댓글, 대댓글 조회 api 추가
- 댓글 offset 기반 조회 방식 api 추가
- 대댓글 cursor 기반 조회 방식 api 추가
> [SWM-104]: 댓글, 대댓글 조회 api 추가

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomDayOffResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomDetailResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomImageResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomOptionInfoResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomReserveTypeResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomTypeInfoResponse.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoom.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomDayOffRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomImageRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomOptionInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReserveTypeRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomTypeInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomQueryService.java
스터디 룸 상세조회 API 개발
- 스터디 룸 상세조회 API 개발
> [FEAT/SWM-103] 스터디 룸 상세조회 API 개발

- src/main/java/com/jj/swm/domain/study/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/repository/CommentRepository.java
- src/main/java/com/jj/swm/domain/study/repository/RecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyBookmarkRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyImageRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyTagRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
> [SWM-105]: 스터디 삭제 api 추가

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomReviewCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/CreateStudyRoomReviewRequest.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/CreateStudyRoomReviewResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/DeleteStudyRoomReviewResponse.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoom.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReviewImage.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomDayOffRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomImageRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomOptionInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReserveTypeRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReviewImageRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReviewReplyRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReviewRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomTagRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomTypeInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/jdbc/JdbcReviewImageRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/jdbc/impl/JdbcReviewImageRepositoryImpl.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewCommandService.java
- src/main/resources/db/migration/V20241219131139__create_study_room_review_image.sql
스터디 룸 이용후기 이미지 엔티티 추가 및 이용후기 관련 로직 수정
- 스터디 룸 삭제 로직 일부 수정
- 스터디 룸 이용후기 이미지 엔티티 생성 및 생성 로직 추가
- 스터디 룸 이용후기 이미지 생성 로직 및 이용후기/답글 삭제 로직 추가
> [FEAT/SWM-107] 스터디 룸 이용후기 이미지 엔티티 추가 및 이용후기 관련 로직 수정

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQnaQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomReviewCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomReviewQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomQnaResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomReviewReplyResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomReviewResponse.java
- src/main/java/com/jj/swm/domain/studyroom/entity/StudyRoomReview.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomQnaRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReviewRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaQueryService.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewQueryService.java
- src/main/java/com/jj/swm/domain/user/dto/response/UserInfoResponse.java
스터디 룸 QnA, 이용후기 READ API(페이지네이션)
- 스터디 룸 QnA, 이용후기 READ API(페이지네이션)
> [FEAT/SWM-106] 스터디 룸 QnA, 이용후기 READ API(페이지네이션)

- Dockerfile
ChromeDriver 설치 Dockerfile에서 제외로 Docker Image 경량화
- Docker Image 경량화
> [SWM-119] Dockerfile 경량화

- Dockerfile
Chrome 설치 후 제거
- Chrome 설치 후 제거
> [SWM-119] Docker Image 경량화

- Dockerfile
도커 이미지 빌드 시 서버 빌드 제거, 이미지 경량화
- 이미지 경량화
> [SWM-121] 도커 이미지 경량화

- src/main/java/com/jj/swm/domain/studyroom/dto/response/UpdateStudyRoomQnaResponse.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/UpdateStudyRoomReviewResponse.java
스터디 룸 업데이트 날짜 형식 통일
- 스터디 룸 업데이트 날짜 형식 통일
> [REFACTOR/SWM-122] 스터디 룸 업데이트 날짜 형식 통일

- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomReviewRepository.java
스터디 룸 이미지 이용후기 쿼리 개선
- 스터디 룸 이미지 이용후기 쿼리 개선
> [FIX/SWM-122] 스터디 룸 이미지 이용후기 쿼리 개선

- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaQueryService.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomQueryService.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewQueryService.java
- src/main/java/com/jj/swm/global/common/enums/PageSize.java
- src/main/resources/application.yml
페이지 크기 공통 관리 Utility 생성
- 페이지 크기 공통 관리 Utility 생성
> [REFACTOR/SWM-122] 페이지 크기 공통 관리 Utility 생성

- src/main/java/com/jj/swm/domain/user/service/UserCommandService.java
- src/main/java/com/jj/swm/global/common/service/EmailService.java
- src/main/java/com/jj/swm/global/config/AsyncConfig.java
유저 이메일 전송 작업 비동기로 변경
- 유저 이메일 전송 작업 비동기로 변경
- 비동기 config 및 예외처리 구현
> [FEAT/SWM-124] 유저 이메일 전송 작업 비동기로 변경

- src/main/java/com/jj/swm/crawling/naver/map/service/NaverMapCrawlingService.java
- src/main/java/com/jj/swm/domain/external/study/controller/ExternalStudyController.java
- src/main/java/com/jj/swm/infra/s3/S3ClientWrapper.java
네이버 지도 썸네일 화질 좋은 것 크롤링, PutObject 시 HeadObject 먼저 하고 Object 없을 시 업로드
- 화질 좋은 이미지 업로드
> [SWM-126] 네이버 지도 크롤링 썸네일 화질 좋은 것으로 교체, 이미 있으면 업로드 스킵

- src/main/java/com/jj/swm/domain/user/controller/UserCommandController.java
- src/main/java/com/jj/swm/domain/user/dto/request/UpgradeRoomAdminRequest.java
- src/main/java/com/jj/swm/domain/user/dto/response/BusinessCheckResponse.java
- src/main/java/com/jj/swm/domain/user/entity/User.java
- src/main/java/com/jj/swm/domain/user/service/BusinessStatusService.java
- src/main/java/com/jj/swm/domain/user/service/UserCommandService.java
- src/main/java/com/jj/swm/global/common/enums/ErrorCode.java
- src/main/java/com/jj/swm/global/security/AllowedPaths.java
- src/main/java/com/jj/swm/global/security/jwt/JwtAuthenticationFilter.java
유저 사업자 검증 및 권한 상승 API 추가
- 유저 사업자 검증 및 권한 상승 API 추가
- Security Filter 일부 수정
> [FEAT/SWM-125] 유저 사업자 검증 및 권한 상승 API 추가

- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomQnaResponse.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaQueryServiceIntegrationTest.java
스터디 룸 QnA 테스트 작성
- 스터디 룸 QnA 테스트 작성
> [TEST/SWM-131] 스터디 룸 QnA 테스트 작성

- .github/workflows/swm-prod-cd.yml
- .github/workflows/swm-prod-ci.yml
Prod CI/CD 워크플로우 생성
- Prod CI/CD 워크플로우 생성
> [INFRA] Prod CI/CD 워크플로우 생성 

- src/main/java/com/jj/swm/crawling/holaworld/service/HolaWorldCrawlingService.java
- src/main/java/com/jj/swm/domain/external/study/dto/response/ExternalStudyDto.java
- src/main/java/com/jj/swm/domain/external/study/enums/Role.java
- src/main/java/com/jj/swm/domain/external/study/enums/Technology.java
- src/main/java/com/jj/swm/global/security/AllowedPaths.java
AllowedPaths 리팩토링
부 스터디 기술, 역할 Enum화
- AllowedPaths 리팩토링
- 부 스터디 기술, 역할 Enum화
> [SWM-138] AllowedPaths 리팩토링 및 외부 스터디 기술, 역할 Enum화

- src/main/java/com/jj/swm/domain/user/repository/UserCredentialRepository.java
- src/test/java/com/jj/swm/global/security/jwt/JwtProviderTest.java
JwtProvider 테스트 작성
- JwtProvider 테스트 작성
> [REFACTOR/SWM-139] JwtProvider 테스트 작성

- src/test/java/com/jj/swm/config/TestConfig.java
- src/test/java/com/jj/swm/config/auth/AuthTestConfig.java
- src/test/java/com/jj/swm/domain/auth/service/AuthServiceTest.java
AuthService 테스트 코드 작성
- AuthService 테스트 코드 작성
> [REFACTOR/SWM-139] AuthService 테스트 코드 작성 

- src/main/java/com/jj/swm/global/config/SecurityConfig.java
유저 권한 계층 구조 추가
- 유저 권한 계층 구조 추가
> [HOTFIX/SWM-142] 유저 권한 계층 구조 추가

- src/main/java/com/jj/swm/domain/studyroom/dto/GetStudyRoomCondition.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/CreateStudyRoomRequest.java
- src/main/java/com/jj/swm/domain/studyroom/entity/embeddable/Address.java
- src/main/java/com/jj/swm/domain/studyroom/repository/custom/impl/CustomStudyRoomRepositoryImpl.java
- src/main/java/com/jj/swm/domain/user/service/BusinessStatusService.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQueryServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/user/service/BusinessStatusServiceTest.java
스터디 룸 목록 조회에 locality 조건 추가
- 스터디 룸 목록 조회에 locality 조건 추가
- 사업자 인증 로직에서 문자열 동적 반복 heap 생성 방지
- locality 조건 추가에 따른 테스트 코드 작성
> [FEAT/SWM-141] 스터디 룸 목록 조회에 locality 조건 추가

- src/main/java/com/jj/swm/global/config/SwaggerConfig.java
Swagger enumAsRef global 세팅
- Swagger enumAsRef global 세팅
> [SWM-147] Swagger enumAsRef global 세팅

- build.gradle
- src/main/java/com/jj/swm/domain/auth/service/AuthService.java
- src/main/java/com/jj/swm/domain/user/controller/UserCommandController.java
- src/main/java/com/jj/swm/domain/user/dto/event/BusinessInspectionUpdateEvent.java
- src/main/java/com/jj/swm/domain/user/dto/event/BusinessVerificationRequestEvent.java
- src/main/java/com/jj/swm/domain/user/dto/response/GetBusinessVerificationRequestResponse.java
- src/main/java/com/jj/swm/domain/user/entity/BusinessVerificationRequest.java
- src/main/java/com/jj/swm/domain/user/entity/InspectionStatus.java
- src/main/java/com/jj/swm/domain/user/entity/User.java
- src/main/java/com/jj/swm/domain/user/repository/BusinessVerificationRequestRepository.java
- src/main/java/com/jj/swm/domain/user/repository/UserRepository.java
- src/main/java/com/jj/swm/domain/user/service/UserCommandService.java
- src/main/java/com/jj/swm/global/common/service/DiscordNotificationService.java
- src/main/java/com/jj/swm/global/common/service/EmailService.java
- src/main/java/com/jj/swm/global/event/handler/BusinessVerificationEventHandler.java
- src/main/java/com/jj/swm/global/security/jwt/JwtProvider.java
- src/main/resources/db/migration/V20250123154401__alter_table_business_verification_request_add_column_user_email.sql
- src/main/resources/templates/emails/auth-code-email.html
- src/main/resources/templates/emails/business-verification-email.html
- src/main/resources/templates/emails/retrieve-email.html
- src/test/java/com/jj/swm/IntegrationContainerSupporter.java
- src/test/java/com/jj/swm/domain/user/service/UserCommandServiceIntegrationTest.java
사업자 검수 요청 승인/거부 작업 ApplicationEventPublisher 활용 이메일 전송
- 사업자 검수 요청 승인/거부 작업 ApplicationEventPublisher 활용 이메일 전송
- Context Caching을 위해 추상 클래스에 MockitoBean 추가
- Thymeleaf 활용 HTML 이메일 전송 코드 변경
- 사업자 검수 요청 테이블에 유저 이메일 추가
> [FEAT/SWM-146] 사업자 검수 요청 승인/거부 작업 ApplicationEventPublisher 활용 이메일 전송

- src/main/java/com/jj/swm/domain/user/entity/BusinessVerificationRequest.java
- src/main/java/com/jj/swm/domain/user/entity/User.java
- src/main/java/com/jj/swm/domain/user/repository/UserCredentialRepository.java
- src/main/java/com/jj/swm/domain/user/service/UserCommandService.java
- src/test/java/com/jj/swm/domain/user/service/UserCommandServiceIntegrationTest.java
Email을 Fetch Join으로 가져오는 것에서 조회로 변경
- Email을 Fetch Join으로 가져오는 것에서 조회로 변경
- Email 조회 로직 변경에 따른 테스트 수정
> [FEAT/SWM-146] Email을 Fetch Join으로 가져오는 것에서 조회로 변경

- src/main/java/com/jj/swm/domain/user/dto/request/UpdateUserPasswordRequest.java
- src/main/java/com/jj/swm/domain/user/service/UserCommandService.java
- src/test/java/com/jj/swm/domain/user/service/UserCommandServiceIntegrationTest.java
비밀번호 변경시 비밀번호 검증 추가
- 비밀번호 변경시 비밀번호 검증 추가
> [FEAT/SWM-148] 비밀번호 변경시 비밀번호 검증 추가

- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomResponse.java
스터디 룸 목록 조회 반환에 주소 및 전화번호 추가
- 스터디 룸 목록 조회 반환에 주소 및 전화번호 추가
> [REFACTOR/SWM-149] 스터디 룸 목록 조회 반환에 주소 및 전화번호 추가

- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomDayOffRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomOptionInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/repository/StudyRoomTypeInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandService.java
- src/main/resources/db/migration/V20250129144613__alter_study_room_option_info_table_add_unique_constraint.sql
- src/main/resources/db/migration/V20250129145221__alter_study_room_day_off_table_add_unique_constraint.sql
- src/main/resources/db/migration/V20250129145333__alter_study_room_type_info_table_add_unique_constraint.sql
- src/test/java/com/jj/swm/domain/studyroom/fixture/StudyRoomFixture.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandServiceIntegrationTest.java
스터디 룸 옵션, 휴무일, 타입 중복 방지 작업
- 스터디 룸 옵션, 휴무일, 타입 테이블에 UNIQUE CONSTRAINT 추가
- 스터디 룸 옵션, 휴무일, 타입 존재 확인 repository 메소드 추가
- 스터디 룸 옵션, 휴무일, 타입 중복 검증 비즈니스 로직 추가
- 스터디 룸 옵션 휴무일, 타입 중복 검증 테스트 코드 작성
> [REFACTOR/SWM-150] 스터디 룸 옵션, 휴무일, 타입 중복 방지 작업

- src/main/java/com/jj/swm/global/config/OAuth2AuthorizedClientServiceConfig.java
- src/main/java/com/jj/swm/global/config/SecurityConfig.java
- src/main/resources/db/migration/V20250201134604__create_oauth2_authorized_client_table.sql
OAuth2 토큰 저장 방식 인메모리에서 DB로 변경
- OAuth2 토큰 저장 방식 인메모리에서 DB로 변경
> [REFACTOR/SWM-152] OAuth2 토큰 저장 방식 인메모리에서 DB로 변경

- src/main/java/com/jj/swm/domain/study/service/CommentQueryService.java
- src/main/java/com/jj/swm/domain/study/service/StudyQueryService.java
- src/main/java/com/jj/swm/global/common/enums/PageSize.java
- src/main/resources/application.yml
page size 값 할당 형식 변경 ( yaml -> 클래스 상수 )
- study page size 값 할당 방식 변경 ( yaml -> 클래스 상수 )
> [REFACTOR/SWM-155]: page size 값 할당 형식 변경 ( yaml -> 클래스 상수 )

- src/main/java/com/jj/swm/global/config/SecurityConfig.java
study 관련 조회 시 비인증 접근 허용
- study 관련 조회 시 비인증 접근 허용
> [FEAT/SWM-156]: study 관련 조회 시 비인증 접근 허용

- src/main/java/com/jj/swm/domain/user/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/dto/response/GetUserInfoResponse.java
- src/main/java/com/jj/swm/domain/user/service/UserQueryService.java
- src/test/java/com/jj/swm/domain/auth/service/AuthServiceTest.java
- src/test/java/com/jj/swm/domain/study/service/StudyCommandServiceConcurrencyTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQnaQueryServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomReviewQueryServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/user/fixture/UserFixture.java
- src/test/java/com/jj/swm/domain/user/service/UserCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/user/service/UserQueryServiceIntegrationTest.java
- src/test/java/com/jj/swm/global/security/jwt/JwtProviderTest.java
유저 정보 반환 API 추가
- 유저 정보 반환 로직 추가
- UserFixture 유저 권한 별 메소드 분리
- 유저 정보 응답 로직 추가에 의한 테스트 작성
> [FEAT/SWM-158] 유저 정보 반환 API 추가

- src/main/java/com/jj/swm/domain/study/service/StudyQueryService.java
스터디 목록 조회 메소드에서 study 조회할 때 비어있으면 예외 발생 대신 빈 리스트 반환으로 변경
- 스터디 목록 조회 메소드에서 study 조회할 때 비어있으면 예외 발생 대신 빈 리스트 반환으로 변경
> [HOTFIX/SWM-161]: 스터디 목록 조회시 404 에러 수정

- src/main/java/com/jj/swm/global/config/SecurityConfig.java
유저 정보 조회 API 인증 적용
- 유저 정보 조회 API 인증 적용
> [HOTFIX/SWM-162] 유저 정보 조회 API 인증 적용

- src/main/java/com/jj/swm/crawling/holaworld/service/HolaWorldCrawlingService.java
홀라 CSS 변경으로 인한 크롤링 코드 수정
- 홀라 CSS 변경으로 인한 크롤링 코드 수정
> 홀라 CSS 변경으로 인한 크롤링 코드 수정

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/GetStudyRoomCondition.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/CreateStudyRoomRequest.java
스터디 룸 생성/조회 유효성 검증 추가
- 스터디 룸 생성/조회 유효성 검증 추가
> [REFACTOR/SWM-164] 스터디 룸 생성/조회 유효성 검증 추가

- src/main/java/com/jj/swm/domain/auth/controller/AuthController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQnaCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQnaQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomReviewCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomReviewQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/GetStudyRoomCondition.java
- src/main/java/com/jj/swm/domain/studyroom/dto/request/CreateStudyRoomRequest.java
- src/main/java/com/jj/swm/domain/user/controller/UserCommandController.java
- src/main/java/com/jj/swm/domain/user/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/dto/request/UpgradeRoomAdminRequest.java
스웨거 API 명세 작업
- 스터디 룸 스웨거 API 명세 작업
- 스터디 룸 이용후기 스웨거 API 명세 작업
- 스터디 룸 QnA 스웨거 API 명세 작업
- 유저 스웨거 API 명세 작업
- Auth 스웨거 API 명세 작업
> [DOCS/SWM-160] 스웨거 API 명세 작업

- src/main/java/com/jj/swm/domain/user/controller/UserCommandController.java
유저 사업자 검수 요청 HTTP Method로 변경
- 유저 사업자 검수 요청 POST Method로 변경
> [REFACTOR/SWM-165] 유저 사업자 검수 요청 HTTP Method로 변경

- src/main/java/com/jj/swm/domain/studyroom/dto/GetStudyRoomCondition.java
스터디 룸 조회 유효성 수정
- 스터디 룸 조회 유효성 수정
> [HOTFIX/SWM-167] 스터디 룸 조회 유효성 수정

- src/main/java/com/jj/swm/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyUpdateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/resources/db/migration/V20250207185133__alter_table_study_drop_thumbnail.sql
- src/test/java/com/jj/swm/domain/study/StudyFixture.java
스터디 테이블 썸네일 삭제
- 스터디 entity thumbnail 필드 삭제
- flyway 통헤 study 테이블 thumbnail 컬럼 삭제
> [HOTFIX/SWM-169]: 스터디 테이블 썸네일 삭제

- src/main/java/com/jj/swm/domain/study/repository/CustomStudyRepositoryImpl.java
페이지네이션 중 1:N fetch join 삭제
- 페이지네이션 중 1:N fetch join 삭제
> [HOTFIX/SWM-171]: 페이지네이션 중 1:N fetch join 삭제

- src/main/java/com/jj/swm/domain/study/dto/request/StudyCreateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/request/StudyUpdateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyDetailsResponse.java
- src/main/java/com/jj/swm/domain/study/dto/response/StudyInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/entity/Study.java
- src/main/java/com/jj/swm/domain/study/repository/CustomStudyRepository.java
- src/main/java/com/jj/swm/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/repository/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/service/CommentCommandService.java
- src/main/java/com/jj/swm/domain/study/service/StudyCommandService.java
- src/main/java/com/jj/swm/domain/study/service/StudyQueryService.java
- src/main/resources/db/migration/V20250207185133__alter_table_study_drop_thumbnail.sql
- src/test/java/com/jj/swm/domain/study/StudyFixture.java
스터디 도메인 수정
- 스터디 thumbnail 삭제
- 스터디 조회 때 유저 정보 포함 위치 변경
- 페이지네이션 중 1:N fetch join 문제 해결
> [HOTFIX/SWM-168]: 스터디 도메인 수정

- src/main/java/com/jj/swm/domain/study/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyQueryService.java
- src/main/java/com/jj/swm/domain/user/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/service/UserQueryService.java
유저가 좋아요한 스터디 목록 조회 추가
- 유저가 좋아요한 스터디 목록 조회 추가
> [FEAT/SWM-154]: 유저가 좋아요한 스터디 목록 조회 추가

- src/main/java/com/jj/swm/domain/study/dto/response/StudyInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/repository/StudyBookmarkRepository.java
- src/main/java/com/jj/swm/domain/user/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/service/UserQueryService.java
유저가 북마크한 스터디 목록 조회 추가
- 유저가 북마크한 스터디 목록 조회 추가
> [FEAT/SWM-173]: 유저가 북마크한 스터디 목록 조회 추가

- src/main/java/com/jj/swm/domain/study/dto/response/StudyInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/repository/StudyBookmarkRepository.java
- src/main/java/com/jj/swm/domain/study/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/service/StudyQueryService.java
- src/main/java/com/jj/swm/domain/user/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/service/UserQueryService.java
유저가 좋아요한, 북마크한 스터디 목록 조회
- 유저가 좋아요한 스터디 목록 조회
- 유저가 북마크한 스터디 목록 조회
> [FEAT/SWM-153]: 유저가 좋아요한, 북마크한 스터디 목록 조회

- src/main/java/com/jj/swm/domain/study/controller/comment/CommentQueryController.java
- src/main/java/com/jj/swm/domain/study/dto/comment/response/CommentInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/dto/comment/response/CommentUpdateResponse.java
- src/main/java/com/jj/swm/domain/study/dto/comment/response/ParentCommentInquiryResponse.java
- src/main/java/com/jj/swm/domain/study/dto/core/response/StudyDetailsResponse.java
- src/main/java/com/jj/swm/domain/study/entity/comment/StudyComment.java
- src/main/java/com/jj/swm/domain/study/repository/comment/CommentRepository.java
- src/main/java/com/jj/swm/domain/study/repository/comment/CustomCommentRepository.java
- src/main/java/com/jj/swm/domain/study/repository/comment/CustomCommentRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/repository/core/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/service/comment/CommentCommandService.java
- src/main/java/com/jj/swm/domain/study/service/comment/CommentQueryService.java
- src/main/java/com/jj/swm/domain/study/service/core/StudyCommandService.java
- src/main/java/com/jj/swm/domain/study/service/core/StudyQueryService.java
- src/main/java/com/jj/swm/global/common/dto/PageResponse.java
스터디 댓글 파트 전체 리팩토링
- 스터디 댓글 파트 전체 리팩토링
> [REFACTOR/SWM-175]: 스터디 댓글 파트 전체 리팩토링

- src/main/java/com/jj/swm/domain/file/controller/FileController.java
- src/main/java/com/jj/swm/domain/file/dto/response/GetPresignedUrlResponse.java
- src/main/java/com/jj/swm/domain/file/service/FileService.java
- src/main/java/com/jj/swm/global/config/SecurityConfig.java
- src/main/java/com/jj/swm/infra/s3/S3ClientWrapper.java
Presigned Url 기능 개발
- Presigned Url 기능 개발
> [SWM-166] minIO presigned Url

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/dto/GetStudyRoomCondition.java
- src/main/java/com/jj/swm/domain/studyroom/dto/SortCriteria.java
- src/main/java/com/jj/swm/domain/studyroom/dto/response/GetStudyRoomResponse.java
- src/main/java/com/jj/swm/domain/studyroom/repository/custom/impl/CustomStudyRoomRepositoryImpl.java
- src/main/resources/db/migration/V20250210133214__alter_table_study_room_add_index_price_desc_for_cursor.sql
- src/test/java/com/jj/swm/domain/studyroom/fixture/StudyRoomFixture.java
- src/test/java/com/jj/swm/domain/studyroom/service/StudyRoomQueryServiceIntegrationTest.java
가격 내림차순 정렬 옵션 추가
- 가격 내림차순 정렬 추가에 따른 필드 추가
- 가격 내림차순 정렬 추가 Cursor 인덱스 추가
- 관련 테스트 작성
- 정렬 별 사용 필드 문서화
> [FEAT/SWM-179] 가격 내림차순 정렬 옵션 추가

- src/main/java/com/jj/swm/domain/studyroom/controller/StudyRoomQueryController.java
스터디 룸 정렬 문서 추가 설명 작성
- 스터디 룸 정렬 문서 추가 설명 작성
> [DOCS/SWM-180] 스터디 룸 정렬 문서 추가 설명 작성

- src/main/java/com/jj/swm/domain/study/controller/core/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/controller/core/StudyQueryController.java
- src/main/java/com/jj/swm/domain/study/controller/recruitmentposition/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/domain/study/dto/core/request/StudyCreateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/recruitmentposition/request/RecruitPositionCreateRequest.java
- src/main/java/com/jj/swm/domain/study/dto/recruitmentposition/request/RecruitPositionUpdateRequest.java
- src/main/java/com/jj/swm/domain/study/entity/recruitmentposition/StudyRecruitmentPosition.java
- src/main/java/com/jj/swm/domain/study/repository/core/CustomStudyBookmarkRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/repository/core/CustomStudyRepository.java
- src/main/java/com/jj/swm/domain/study/repository/core/CustomStudyRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/repository/core/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/repository/core/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/repository/jdbc/JdbcRecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/repository/jdbc/JdbcRecruitmentPositionRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/service/core/StudyCommandService.java
- src/main/java/com/jj/swm/domain/study/service/core/StudyQueryService.java
- src/main/java/com/jj/swm/domain/study/service/recruitmentposition/RecruitmentPositionCommandService.java
스터디 핵심 파트 전체 리팩토링
- 스터디 핵심 파트 전체 리팩토링
> [REFACTOR/SWM-178]: 스터디 핵심 파트 전체 리팩토링

- src/main/java/com/jj/swm/domain/study/repository/recruitmentposition/RecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/service/recruitmentposition/RecruitmentPositionCommandService.java
스터디 모집 포지션 파트 전체 리팩토링
- 스터디 모집 포지션 파트 전체 리팩토링
> [REFACTOR/SWM-183]: 스터디 모집 포지션 파트 전체 리팩토링

- src/main/java/com/jj/swm/domain/studyroom/core/controller/StudyRoomQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/core/dto/response/GetStudyRoomResponse.java
- src/main/java/com/jj/swm/domain/studyroom/core/repository/StudyRoomBookmarkRepository.java
- src/main/java/com/jj/swm/domain/studyroom/core/repository/StudyRoomLikeRepository.java
- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomQueryService.java
- src/main/java/com/jj/swm/domain/user/core/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/core/service/UserQueryService.java
- src/test/java/com/jj/swm/domain/studyroom/core/service/StudyRoomQueryServiceIntegrationTest.java
특정 유저의 좋아요, 북마크 스터디 룸 조회 작업
- 특정 유저가 북마크한 스터디 룸 반환 로직 추가
- 특정 유저가 좋아요한 스터디 룸 반환 로직 추가
- 관련 테스트 작성
- 추가된 API들에 관한 Swagger 문서 작성
> [FEAT/SWM-188] 특정 유저의 좋아요, 북마크 스터디 룸 조회 작업

- src/main/java/com/jj/swm/domain/study/comment/service/CommentQueryService.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
- src/main/java/com/jj/swm/domain/studyroom/core/constants/StudyRoomConstraints.java
- src/main/java/com/jj/swm/domain/studyroom/core/dto/request/CreateStudyRoomRequest.java
- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomCommandService.java
- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomQueryService.java
- src/main/java/com/jj/swm/domain/studyroom/qna/service/StudyRoomQnaQueryService.java
- src/main/java/com/jj/swm/domain/studyroom/review/service/StudyRoomReviewQueryService.java
- src/main/java/com/jj/swm/domain/user/core/service/UserQueryService.java
- src/main/java/com/jj/swm/global/common/constants/PageSize.java
- src/main/java/com/jj/swm/global/common/util/ListCheckUtils.java
- src/test/java/com/jj/swm/domain/studyroom/qna/service/StudyRoomQnaQueryServiceIntegrationTest.java
스터디 룸 수정 시 개수 제한 리팩토링
- 기존 PageSize 상수 클래스 constants 디렉토리로 이동
- 스터디 룸 수정 시 개수 제한 간 삭제값도 고려하도록 수정
- 중복되는 리스트 검증 코드를 줄이기 위한 ListCheckUtils 생성
- 스터디 룸에서 사용될 범용 상수 클래스 생성 및 적용
> [REFACTOR/SWM-189] 스터디 룸 수정 시 개수 제한 리팩토링

- src/main/java/com/jj/swm/domain/study/constants/StudyElementLimit.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/AddStudyRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/ModifyStudyRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/SaveStudyImageRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/SaveStudyTagRequest.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyImageRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyTagRepository.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyCommandService.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/RecruitmentPositionRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
태그, 이미지, 모집 포지션 제한 개수 변경 및 개수 제한에 대한 예외 처리 추가
- 태그, 이미지, 모집 포지션 제한 개수 변경
- 개수 제한에 대한 예외 처리 추가
> [HOTFIX/SWM-186]: 태그, 이미지, 모집 포지션 제한 개수 변경 및 개수 제한에 대한 예외 처리 추가

- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/request/AddRecruitmentPositionRequest.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/response/FindRecruitmentPositionResponse.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/entity/RecruitmentPositionTitle.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/entity/StudyRecruitmentPosition.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/jdbc/impl/JdbcRecruitmentPositionRepositoryImpl.java
- src/main/resources/db/migration/V20250213191710__alter_table_recruitment_position_table_alter_type_title.sql
모집 포지션명 varchar 타입에서 enum으로 변경
- 모집 포지션명 varchar 타입에서 enum으로 변경
> [HOTFIX/SWM-192]: 모집 포지션명 varchar 타입에서 enum으로 변경

- src/main/java/com/jj/swm/domain/study/core/controller/StudyQueryController.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
- src/main/java/com/jj/swm/domain/user/core/controller/UserQueryController.java
- src/main/java/com/jj/swm/domain/user/core/service/UserQueryService.java
유저 도메인에 있던 좋아요한, 북마크한 스터디 목록 조회 스터디 도메인으로 이동
- 유저 도메인에 있던 좋아요한, 북마크한 스터디 목록 조회 스터디 도메인으로 이동
- loadBookmarkInfoMap 중복 제거
> [HOTFIX/SWM-195]: 유저 도메인에 있던 좋아요한, 북마크한 스터디 목록 조회 스터디 도메인으로 이동

- src/main/java/com/jj/swm/domain/study/core/dto/FindStudyCondition.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/impl/CustomStudyRepositoryImpl.java
스터디 목록 조회 시 제목 검색 필터링 적용
- 스터디 목록 조회 시 제목 검색 필터링 적용
> [HOTFIX/SWM-197]: 스터디 목록 조회 시 제목 검색 필터링 적용

- src/main/java/com/jj/swm/domain/studyroom/core/dto/response/GetStudyRoomDetailResponse.java
스터디 룸 상세조회 오픈/종료 반환 포맷 변경
- 스터디 룸 상세조회 오픈/종료 반환 포맷 변경
> [REFACTOR/SWM-202] 스터디 룸 상세조회 오픈/종료 반환 포맷 변경

- src/main/java/com/jj/swm/domain/study/comment/controller/CommentCommandController.java
- src/main/java/com/jj/swm/domain/study/comment/controller/CommentQueryController.java
- src/main/java/com/jj/swm/domain/study/core/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/core/controller/StudyQueryController.java
- src/main/java/com/jj/swm/domain/study/core/dto/GetStudyCondition.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/global/config/SwaggerConfig.java
스터디 도메인 스웨거 관련 어노테이션 추가
- v1 api 그룹화 설정
- 스터디 도메인 스웨거 어노테이션 추가
> [DOCS/SWM-200]: 스터디 도메인 스웨거 관련 어노테이션 추가

- src/main/java/com/jj/swm/domain/study/core/dto/SortCriteria.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/impl/CustomStudyRepositoryImpl.java
스터디 목록 조회 시 댓글 순 정렬 조건 추가
- 스터디 목록 조회 시 댓글 순 정렬 조건 추가
> [FEAT/SWM-203]: 스터디 목록 조회 시 댓글 순 정렬 조건 추가

- src/main/java/com/jj/swm/domain/study/constants/StudyConstants.java
- src/main/java/com/jj/swm/domain/study/constants/StudyElementLimit.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/CreateStudyRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/SaveStudyImageRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/SaveStudyTagRequest.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyCommandService.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/request/CreateRecruitmentPositionRequest.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/request/UpdateRecruitmentPositionRequest.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
> [REFACTOR/SWM-211]: 스터디 관련 상수 정리

- src/main/java/com/jj/swm/domain/study/core/dto/StudyLikeInfo.java
- src/main/java/com/jj/swm/domain/study/core/dto/response/GetStudyResponse.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/CustomStudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/impl/CustomStudyBookmarkRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/impl/CustomStudyLikeRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
스터디 목록 조회 시 좋아요 여부 정보 추가
- 스터디 목록 조회 시 좋아요 여부 정보 추가
> [FIX/SWM-213]: 스터디 목록 조회 시 좋아요 여부 정보 추가

- src/main/java/com/jj/swm/domain/study/core/dto/StudyLikeInfo.java
- src/main/java/com/jj/swm/domain/study/core/dto/response/GetStudyResponse.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyBookmarkRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/CustomStudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/impl/CustomStudyBookmarkRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/impl/CustomStudyLikeRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
스터디 목록 조회 파트 수정
- 스터디 모집 메인 페이지에서 목록 조회 시 좋아요 여부 정보 추가
- 마이 페이지에서 스터디 모집 목록 조회 시 북마크 정보 삭제
> [HOTFIX/SWM-212]: 스터디 목록 조회 파트 수정

- src/test/java/com/jj/swm/domain/study/core/fixture/StudyFixture.java
- src/test/java/com/jj/swm/domain/study/core/fixture/StudyLikeFixture.java
- src/test/java/com/jj/swm/domain/study/core/service/StudyCommandServiceIntegrationTest.java
> [REFACTOR/SWM-216]: 기존 테스트 리팩토링

- src/main/java/com/jj/swm/domain/studyroom/core/constants/StudyRoomConstants.java
- src/main/java/com/jj/swm/domain/studyroom/core/dto/StudyRoomBookmarkInfo.java
- src/main/java/com/jj/swm/domain/studyroom/core/dto/StudyRoomLikeInfo.java
- src/main/java/com/jj/swm/domain/studyroom/core/dto/request/CreateStudyRoomRequest.java
- src/main/java/com/jj/swm/domain/studyroom/core/dto/response/GetStudyRoomDetailResponse.java
- src/main/java/com/jj/swm/domain/studyroom/core/dto/response/GetStudyRoomResponse.java
- src/main/java/com/jj/swm/domain/studyroom/core/repository/StudyRoomBookmarkRepository.java
- src/main/java/com/jj/swm/domain/studyroom/core/repository/StudyRoomLikeRepository.java
- src/main/java/com/jj/swm/domain/studyroom/core/repository/custom/CustomStudyRoomLikeRepository.java
- src/main/java/com/jj/swm/domain/studyroom/core/repository/custom/impl/CustomStudyRoomLikeRepositoryImpl.java
- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomCommandService.java
- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomQueryService.java
- src/test/java/com/jj/swm/domain/studyroom/core/service/StudyRoomQueryServiceIntegrationTest.java
스터디 룸 조회 로직 수정
- 스터디 룸 목록 조회 시 좋아요 boolean값 반환
- 스터디 룸 상세 조회 시 좋아요 boolean값 반환
- 마이페이지 스터디 룸 조회 시 북마크, 좋아요 값 반환 X
> [REFACTOR/SWM-204] 스터디 룸 조회 로직 수정

- .github/workflows/swm-dev-cd.yml
- .github/workflows/swm-dev-ci.yml
- .github/workflows/swm-prod-cd.yml
- .github/workflows/swm-prod-ci.yml
Github Actions 캐시 모듈 버전 v3로 변경
- Github Actions 캐시 모듈 버전 v3로 변경
- [  ] 🔨 리팩토링
> [CHORE/SWM-225] Github Actions 캐시 모듈 버전 v3로 변경

- src/main/java/com/jj/swm/domain/study/comment/dto/response/CreateCommentResponse.java
- src/main/java/com/jj/swm/domain/study/comment/dto/response/GetCommentResponse.java
- src/main/java/com/jj/swm/domain/study/comment/dto/response/UpdateCommentResponse.java
- src/main/java/com/jj/swm/domain/study/core/dto/response/GetStudyDetailsResponse.java
스터디 모집, 댓글 생성 날짜, 수정 날짜 추가 및 format 변경
- 스터디 모집 상세 조회 생성 날짜, 수정 날짜 추가
- 스터디 모집, 댓글 날짜 포맷 변경
> [HOTFIX/SWM-224]: 스터디 모집, 댓글 생성 날짜, 수정 날짜 추가 및 format 변경

- src/main/java/com/jj/swm/domain/study/comment/repository/CommentRepository.java
- src/main/java/com/jj/swm/domain/study/core/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/DeleteStudyListRequest.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyBookmarkRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyImageRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyLikeRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyTagRepository.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyCommandService.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/RecruitmentPositionRepository.java
스터디 모집 다중 삭제 추가
- 스터디 모집 다중 삭제 추가
> [FEAT/SWM-226]: 스터디 모집 다중 삭제 추가

- src/main/java/com/jj/swm/domain/study/comment/dto/response/UpdateCommentResponse.java
- src/main/java/com/jj/swm/domain/study/comment/service/CommentCommandService.java
- src/test/java/com/jj/swm/domain/study/comment/fixture/request/CommentRequestFixture.java
- src/test/java/com/jj/swm/domain/study/comment/service/CommentCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/study/core/service/StudyCommandServiceIntegrationTest.java
study comment command service 테스트
- 스터디 댓글 생성 서비스 테스트
- 스터디 댓글 수정 서비스 테스트
- 스터디 댓글 삭제 서비스 테스트
> [TEST/SWM-223]: study comment command service 테스트

- src/main/java/com/jj/swm/domain/study/core/controller/StudyCommandController.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyCommandService.java
- src/test/java/com/jj/swm/domain/study/core/fixture/request/StudyRequestFixture.java
- src/test/java/com/jj/swm/domain/study/core/service/StudyCommandServiceIntegrationTest.java
> [TEST/SWM-229]: 스터디 다중 삭제 테스트

- src/test/java/com/jj/swm/domain/study/comment/service/CommentCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/study/core/service/StudyCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandServiceIntegrationTest.java
스터디 관련 테스트 코드 리팩토링
- StudyCommandServiceIntegrationTest 일관화 작업
- CommentCommandServiceIntegrationTest 일관화 작업
- RecruitmentPositionCommandServiceIntegrationTest 일관화 작업
> [REFACTOR/SWM-230] 스터디 관련 테스트 코드 리팩토링

- src/main/java/com/jj/swm/domain/study/core/controller/StudyQueryController.java
- src/main/java/com/jj/swm/domain/study/core/repository/StudyRepository.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
유저가 작성한 스터디 모집 목록 조회 추가
- 유저가 작성한 스터디 모집 목록 조회 추가
> [FEAT/SWM-232]: 유저가 작성한 스터디 모집 목록 조회 추가

- src/main/java/com/jj/swm/domain/studyroom/core/controller/StudyRoomQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/core/repository/StudyRoomRepository.java
- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomQueryService.java
- src/test/java/com/jj/swm/domain/studyroom/core/service/StudyRoomQueryServiceIntegrationTest.java
사업자가 생성한 스터디 룸 목록 조회 추가
- 사업자가 생성한 스터디 룸 목록 조회 추가
- 관련 테스트 작성
> [FEAT/SWM-233] 사업자가 생성한 스터디 룸 목록 조회 추가

- src/main/java/com/jj/swm/domain/common/utils/QueryDSLBooleanUtils.java
- src/main/java/com/jj/swm/domain/study/comment/repository/custom/impl/CustomCommentRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/core/repository/custom/impl/CustomStudyRepositoryImpl.java
nullSafeBuilder 중복 메소드 utils 클래스로 추출
- nullSafeBuilder 중복 메소드 utils 클래스로 추출
> [REFACTOR/SWM-236]: nullSafeBuilder 중복 메소드 utils 클래스로 추출

- src/main/java/com/jj/swm/domain/studyroom/core/controller/StudyRoomCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/core/controller/StudyRoomQueryController.java
- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomCommandService.java
- src/main/java/com/jj/swm/domain/user/core/entity/User.java
- src/main/java/com/jj/swm/domain/user/core/service/UserCommandService.java
- src/main/resources/db/migration/V20250316151657__alter_table_users_modify_column_nickname.sql
- src/test/java/com/jj/swm/domain/studyroom/core/service/StudyRoomCommandServiceIntegrationTest.java
유저 삭제 비즈니스 로직 리팩토링 및 기타 리팩토링
- 유저 삭제 시 스터디 룸 100개씩 끊어서 batch 삭제
- 유저 삭제 시 닉네임 초기화 deleted_uuid_nickname 형식으로 변경
- 스터디 룸 삭제 메서드 네이밍 변경
- 스터디 룸 생성 내역 조회 API docs 작성
> [REFACTOR/SWM-239] 유저 삭제 비즈니스 로직 리팩토링 및 기타 리팩토링

- src/test/java/com/jj/swm/domain/study/comment/service/CommentCommandServiceIntegrationTest.java
- src/test/java/com/jj/swm/domain/study/core/service/StudyCommandServiceIntegrationTest.java
댓글 수 동시성 테스트
- 댓글 생성 동시성 테스트
- 댓글 삭제 동시성 테스트
> [TEST/SWM-241]: 댓글 수 동시성 테스트

- src/main/java/com/jj/swm/domain/studyroom/core/repository/custom/impl/CustomStudyRoomRepositoryImpl.java
스터디 룸에 QueryDSLBooleanBuilder 클래스 적용
- 스터디 룸에 QueryDSLBooleanBuilder 클래스 적용
> [REFACTOR/SWM-245] 스터디 룸에 QueryDSLBooleanBuilder 클래스 적용

- src/main/java/com/jj/swm/domain/study/recruitmentposition/constants/StudyParticipationConstants.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/request/CreateStudyParticipationRequest.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/entity/StudyParticipation.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationAttachmentRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationLinkRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/jdbc/JdbcStudyParticipationAttachmentRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/jdbc/JdbcStudyParticipationAttachmentRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/jdbc/JdbcStudyParticipationLinkRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/jdbc/impl/JdbcStudyParticipationLinkRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
- src/main/resources/db/migration/V20250318214708__alter_sequences_participant_rename_to_participation.sql
- src/test/java/com/jj/swm/domain/study/recruitmentposition/fixture/dto/request/CreateStudyParticipationRequestFixture.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandServiceIntegrationTest.java
스터디 참여 생성 API 구현
- 스터디 참여 생성 API 구현
- cleanUp에서 sequence 네이밍 찾지 못하는 문제 해결
- 스터디 참여 생성 서비스 로직 테스트
> [FEAT/SWM-243]: 스터디 참여 생성 API 구현

- src/main/java/com/jj/swm/domain/study/comment/dto/request/UpsertCommentRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/CreateStudyRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/ModifyStudyImageRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/ModifyStudyTagRequest.java
- src/main/java/com/jj/swm/domain/study/core/dto/request/UpdateStudyRequest.java
문자 길이에 대한 validation 추가
- 문자 길이에 대한 validation 추가
> [FIX/SWM-251]: 문자 길이에 대한 validation 추가

- src/main/resources/db/migration/V20250319202143__alter_table_study_recruitment_position_add_constraint_headcount.sql
study_recruitment_position 테이블 내 headcount 100이하 제약조건 추가
- study_recruitment_position 테이블 내 headcount 100이하 제약조건 추가
> [FIX/SWM-253]: study_recruitment_position 테이블 내 headcount 100이하 제약조건 추가

- src/main/java/com/jj/swm/domain/file/controller/FileController.java
> [SWM-255] 스웨거 설명 실수 고침

- src/main/java/com/jj/swm/domain/studyroom/core/service/StudyRoomCommandService.java
- src/main/java/com/jj/swm/global/security/jwt/JwtAuthenticationFilter.java
미발견 데이터 값 상태 코드 NOT_FOUND로 변경
- 미발견 데이터 값 상태 코드 NOT_FOUND로 변경
> [REFACTOR/SWM-256] 미발견 데이터 값 상태 코드 NOT_FOUND로 변경

- src/main/java/com/jj/swm/domain/studyroom/reservation/controller/StudyRoomReservationCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/dto/event/StudyRoomReservationRequestEvent.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/dto/request/CreateStudyRoomReservationRequest.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/entity/ApprovalStatus.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/entity/StudyRoomReservationInfo.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/repository/StudyRoomReservationInfoRepository.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/service/StudyRoomReservationCommandService.java
- src/main/java/com/jj/swm/global/common/service/KakaoNotificationService.java
- src/main/java/com/jj/swm/global/common/util/RandomUtils.java
- src/main/java/com/jj/swm/global/event/handler/BusinessVerificationEventHandler.java
- src/main/java/com/jj/swm/global/event/handler/StudyRoomReservationEventHandler.java
- src/main/resources/db/migration/V20250318153943__create_study_room_reservation_info_table.sql
- src/test/java/com/jj/swm/IntegrationContainerSupporter.java
- src/test/java/com/jj/swm/domain/studyroom/core/fixture/StudyRoomReserveTypeFixture.java
- src/test/java/com/jj/swm/domain/studyroom/reservation/service/StudyRoomReservationCommandServiceIntegrationTest.java
스터디 룸 예약 생성 API 개발
- 스터디 룸 예약 승인 상태 ENUM 값 변경
- 카카오톡 알림톡 전송 서비스 클래스 뼈대 작성
- 스터디 룸 예약 신청 관련 이벤트 핸들러 등록
- 스터디 룸 예약 신청 API 로직 작성
- 관련 테스트 작성
> [FEAT/SWM-247] 스터디 룸 예약 생성 API 개발

- src/main/java/com/jj/swm/domain/study/comment/repository/StudyStudyCommentRepository.java
- src/main/java/com/jj/swm/domain/study/comment/service/StudyCommentQueryService.java
- src/main/java/com/jj/swm/domain/study/core/dto/response/GetStudyDetailsResponse.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/AcceptedStudyParticipationCountInfo.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/request/UpdateStudyParticipationStatusRequest.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/response/GetRecruitmentPositionDetailsResponse.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/response/UpdateStudyParticipationStatusResponse.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/entity/StudyParticipation.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/entity/StudyRecruitmentPosition.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/jdbc/impl/JdbcRecruitmentPositionRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
- src/main/resources/db/migration/V20250322155011__alter_table_study_recruitment_position_drop_column_accepted_count.sql
- src/test/java/com/jj/swm/domain/study/recruitmentposition/fixture/dto/request/UpdateStudyParticipationStatusRequestFixture.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/fixture/dto/request/UpsertRecruitmentPositionRequestFixture.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandServiceIntegrationTest.java
스터디 참여 상태 수정(승인, 거절) API 개발
- study_recruitment_position 테이블 내 acceptedCount 제거에 따른 로직 수정
- 스터디 참여 상태 수정 api 추가
- 스터디 참여 상태 수정 테스트
- 스터디 참여 상태 수정 구현에 따른 모집 포지션 테스트 추가
- 스터디 참여 상태 수정 구현에 따른 스터디 참여 생성 테스트 추가
> [FEAT/SWM-246]: 스터디 참여 상태 수정(승인, 거절) API 개발

- src/main/java/com/jj/swm/domain/studyroom/reservation/controller/StudyRoomReservationCommandController.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/entity/ApprovalStatus.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/service/StudyRoomReservationCommandService.java
- src/main/java/com/jj/swm/global/config/SecurityConfig.java
- src/main/java/com/jj/swm/global/security/jwt/TokenRedisService.java
- src/main/resources/db/migration/V20250325130017__alter_enum_approval_status_add_canceled.sql
- src/test/java/com/jj/swm/domain/studyroom/reservation/service/StudyRoomReservationCommandServiceIntegrationTest.java
스터디 룸 예약 취소 API 개발
- 스터디 룸 예약 승인 상태 ENUM에 취소 추가
- 스터디 룸 예약 취소 서비스/컨트롤러 로직 작성
- 스터디 룸 예약 정보 승인/거부 시 예약 정보 ID가 아닌 예약 토큰으로 접근하도록 리팩토링
> [FEAT/SWM-260] 스터디 룸 예약 취소 API 개발

- src/main/java/com/jj/swm/domain/study/core/service/StudyCommandService.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/request/ModifyStudyParticipationLinkRequest.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/request/UpdateStudyParticipationRequest.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/entity/StudyParticipation.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationLinkRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/fixture/dto/request/UpdateStudyParticipationRequestFixture.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandServiceIntegrationTest.java
스터디 참여 수정 API 개발
- 스터디 참여 수정 API 추가
- 스터디 참여 수정 서비스 테스트
- Limit에 대한 예외 메세지에 Exceed 대신 Deviation 사용
> [FEAT/SWM-257]: 스터디 참여 수정 API 개발

- src/main/java/com/jj/swm/global/config/SwaggerConfig.java
Swagger에 Auth 정보 표시
- Swagger에 Auth 정보 표시
> [HOTFIX/SWM-263] Swagger에 Auth 정보 표시

- src/main/java/com/jj/swm/domain/studyroom/reservation/dto/event/StudyRoomReservationRequestEvent.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/dto/event/StudyRoomReservationResponseEvent.java
- src/main/java/com/jj/swm/domain/studyroom/reservation/service/StudyRoomReservationCommandService.java
- src/main/java/com/jj/swm/global/common/service/KakaoNotificationService.java
- src/main/java/com/jj/swm/global/event/handler/StudyRoomReservationEventHandler.java
- src/main/java/com/jj/swm/global/security/jwt/TokenRedisService.java
- src/test/java/com/jj/swm/domain/studyroom/reservation/service/StudyRoomReservationCommandServiceIntegrationTest.java
스터디 룸 예약 토큰 Redis 삽입/삭제 시점 리팩토링
- 스터디 룸 예약 토큰 Redis 삽입 시점 이벤트 핸들러로 변경
- 스터디 룸 예약 토큰 Redis 삭제 시점 이벤트 핸들러로 변경
- 스터디 룸 예약 수정 작업에서 승인/거부 작업이 일어났다면 예외 처리
- 관련 테스트 코드 재작성
> [REFACTOR/SWM-266] 스터디 룸 예약 토큰 Redis 삽입/삭제 시점 리팩토링

- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationLinkRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandServiceIntegrationTest.java
스터디 참여 삭제 API 추가
- 스터디 참여 삭제 API 추가
- 스터디 참여 삭제 테스트 추가
> [FEAT/SWM-262]: 스터디 참여 삭제 API 추가

- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandServiceIntegrationTest.java
승인된 참여 신청은 수정 못하도록 로직 변경
- 승인된 참여 신청은 수정 못하도록 로직 변경
- 승인된 참여 신청은 수정 못하도록 로직 변경에 따른 테스트 추가
> [FIX/SWM-269]: 승인된 참여 신청은 수정 못하도록 로직 변경

- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionQueryController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/GetStudyParticipationCondition.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/response/GetStudyParticipationResponse.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/custom/CustomStudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/custom/impl/CustomStudyParticipationRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionQueryService.java
- src/main/java/com/jj/swm/global/common/constants/PageSize.java
스터디 참여 목록 조회 API 개발
- 스터디 참여 목록 조회 API 개발
> [FEAT/SWM-270]: 스터디 참여 목록 조회 API 개발

- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionQueryController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/dto/response/GetStudyParticipationDetailsResponse.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationLinkRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/StudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/custom/CustomStudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/repository/custom/impl/CustomStudyParticipationRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionQueryService.java
스터디 참여 상세 조회 API 개발
- 스터디 참여 상세 조회 API 개발
> [FEAT/SWM-271]: 스터디 참여 상세 조회 API 개발

- src/main/java/com/jj/swm/domain/user/core/dto/response/GetUserInfoResponse.java
- src/main/java/com/jj/swm/domain/user/core/repository/UserCredentialRepository.java
- src/main/java/com/jj/swm/domain/user/core/service/UserQueryService.java
유저 정보 조회 시 유저 이메일도 반환
- 유저 정보 조회 시 유저 이메일도 반환
> [REFACTOR/SWM-273] 유저 정보 조회 시 유저 이메일도 반환

- src/main/java/com/jj/swm/domain/study/recruitmentposition/controller/RecruitmentPositionCommandController.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/entity/StudyParticipation.java
- src/main/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandService.java
- src/test/java/com/jj/swm/domain/study/recruitmentposition/service/RecruitmentPositionCommandServiceIntegrationTest.java
스터디 참여 모집 포지션 변경 API 개발
- 스터디 참여 모집 포지션 변경 API 개발
> [FEAT/SWM-274]: 스터디 참여 모집 포지션 변경 API 개발

- src/main/java/com/jj/swm/domain/study/participation/dto/GetStudyParticipationCondition.java
- src/main/java/com/jj/swm/domain/study/participation/repository/custom/CustomStudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/participation/repository/custom/impl/CustomStudyParticipationRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/participation/service/StudyParticipationQueryService.java
참여 신청 목록 조회 offset 방식으로 변경
- 참여 신청 목록 조회 offset 방식으로 변경
> [FIX/SWM-280]: 참여 신청 목록 조회 offset 방식으로 변경

- src/main/java/com/jj/swm/domain/study/core/dto/response/GetStudyResponse.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
- src/main/java/com/jj/swm/domain/study/participation/controller/StudyParticipationQueryController.java
- src/main/java/com/jj/swm/domain/study/participation/dto/response/GetStudyParticipationInMyPageResponse.java
- src/main/java/com/jj/swm/domain/study/participation/repository/StudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/participation/repository/custom/CustomStudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/participation/repository/custom/impl/CustomStudyParticipationRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/participation/service/StudyParticipationQueryService.java
마이페이지 내 참여 관련 조회 API 개발
- 마이페이지 내 참여 신청 목록 조회
- 사용자가 신청한 스터디 목록 조회
> [FEAT/SWM-281]: 마이페이지 내 참여 관련 조회 API 개발

- src/main/java/com/jj/swm/domain/study/core/dto/response/GetRecruitmentPositionDetailsResponse.java
- src/main/java/com/jj/swm/domain/study/core/service/StudyQueryService.java
- src/main/java/com/jj/swm/domain/study/participation/dto/StudyParticipationCountInfo.java
- src/main/java/com/jj/swm/domain/study/participation/repository/StudyParticipationRepository.java
스터디 상세 조회 시 모집 포지션에 대한 참여 신청 개수 데이터 추가
- 스터디 상세 조회 시 모집 포지션에 대한 참여 신청 개수 데이터 추가
> [FIX/SWM-283]: 스터디 상세 조회 시 모집 포지션에 대한 참여 신청 개수 데이터 추가

- src/main/java/com/jj/swm/domain/study/participation/controller/StudyParticipationCommandController.java
- src/main/java/com/jj/swm/domain/study/participation/repository/StudyParticipationRepository.java
- src/main/java/com/jj/swm/domain/study/participation/repository/jdbc/impl/JdbcStudyParticipationLinkRepositoryImpl.java
- src/main/java/com/jj/swm/domain/study/participation/service/StudyParticipationCommandService.java
스터디 참여 파트 리팩토링
- 스터디 참여 파트 리팩토링
> [REFACTOR/SWM-285]: 스터디 참여 파트 리팩토링
